const labels: Record<string, string> = {
  APPROVED: "Aprobada",
  REJECTED: "Rechazada",
  PENDING: "Pendiente",
  UNDER_REVIEW: "En revisión",
  NEEDS_INFO: "Falta información",
  DRAFT: "Borrador",
  ACTIVE: "Activa",
  SUSPENDED: "Suspendida",
  BLOCKED: "Bloqueada",
  FREE: "Free",
  LITE: "Lite",
  BUSINESS: "Business",
  ENTERPRISE: "Enterprise",
  FREE_REGISTRATION: "Registro gratuito",
  DIRECT_PURCHASE: "Compra online",
  MANUAL_GRANT: "Asignación manual",
  NUBRA_BASIC_BUNDLE: "Paquete Nubra Basic",
  NUBRA_ENTERPRISE_BUNDLE: "Paquete Nubra Enterprise",
  PROMOTION: "Promoción",
  MIGRATION: "Migración",
  SUPER_ADMIN: "Administrador general",
  OPERATIONS_ADMIN: "Administración operativa",
  BILLING_ADMIN: "Facturación",
  SALES_ADMIN: "Gestión comercial",
  REVIEWER: "Revisión de solicitudes",
  SUPPORT_ADMIN: "Soporte",
  SECURITY_ADMIN: "Seguridad",
  "subscription.changed": "Suscripción actualizada",
  "subscription.paid": "Suscripción activada por pago",
  "application.approved": "Solicitud aprobada",
  "application.rejected": "Solicitud rechazada",
  "application.needs_info": "Se solicitó más información",
  "application.under_review": "Solicitud en revisión",
  "application.submitted": "Solicitud enviada",
  "application.saved": "Solicitud guardada",
  "organization.created": "Negocio creado",
  "organization.updated": "Datos del negocio actualizados",
  "organization.active": "Negocio activado",
  "organization.suspended": "Negocio suspendido",
  "organization.blocked": "Negocio bloqueado",
  "sales.pos_created": "Venta rápida registrada",
  "payments.created": "Cobro registrado",
  "suppliers.created": "Proveedor creado",
  "suppliers.updated": "Proveedor actualizado",
  "suppliers.archived": "Proveedor archivado",
  "sales.created": "Venta registrada",
  "sales.cancelled": "Venta cancelada",
  "products.created": "Producto creado",
  "products.updated": "Producto actualizado",
  "customers.created": "Cliente creado",
  "customers.updated": "Cliente actualizado",
  "inventory.created": "Movimiento de inventario registrado",
};
export function displayLabel(value: string) {
  return labels[value] ?? value.replaceAll("_", " ").replaceAll(".", " · ");
}
export const businessFields: Record<string, string> = {
  name: "Nombre comercial",
  legalName: "Razón social",
  taxId: "CUIT",
  sector: "Rubro",
  description: "Descripción",
  email: "Email",
  phone: "Teléfono",
  whatsapp: "WhatsApp",
  address: "Dirección",
  city: "Localidad",
  province: "Provincia",
  country: "País",
  postalCode: "Código postal",
  website: "Sitio web",
  instagram: "Instagram",
  facebook: "Facebook",
  tiktok: "TikTok",
  employees: "Personas en el equipo",
  businessType: "Tipo de negocio",
  physicalStore: "Local físico",
  ecommerce: "Venta online",
  branches: "Sucursales",
  responsibleName: "Responsable",
  responsiblePhone: "Teléfono del responsable",
  referral: "Cómo conoció Nubra",
  notes: "Notas",
  currency: "Moneda",
  timezone: "Zona horaria",
};
export function displayValue(value: unknown) {
  return typeof value === "boolean"
    ? value
      ? "Sí"
      : "No"
    : value === null || value === undefined || value === ""
      ? "Sin informar"
      : String(value);
}
